# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['deepcode_main.py'],
    pathex=['src'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'deepcode',
        'deepcode.api',
        'deepcode.chat',
        'deepcode.cli',
        'deepcode.models',
        'deepcode.renderer',
        'deepcode.storage',
        'prompt_toolkit',
        'prompt_toolkit.history',
        'prompt_toolkit.styles',
        'rich',
        'rich.console',
        'rich.markdown',
        'rich.panel',
        'rich.text',
        'rich.style',
        'rich.box',
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'anyio',
        'anyio._backends._asyncio',
        'appdirs',
        'pkg_resources',
        'pkg_resources.extern',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='deepcode',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
